### PR TITLE
add exiv2-0.27.0 support

### PR DESCRIPTION
**Pull request by linxon**

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
Hi @linxon , I was curious about something.  Did you open and close this request yourself?  I'm double-checking that we didn't accidentally deploy or configure something the other day that may auto-close a request.

**Comment by linxon** [comment]
`exiv2` supports `pkg-config` and i would like later to add version checking using autotools

**Comment by ajnelson-nist** [comment]
Ah, ok.  Thank you.

**Comment by ajnelson-nist** [comment]
Hi, @linxon .  I looked over the commit and updated the CI tests in [this branch](https://github.com/ajnelson-nist/dfxml/tree/check_for_recent_exiv2_version).  I don't understand the desired outcome in these scenarios:

* exiv2 >= 0.27 present -> support exiv2 features
* exiv2 < 0.27 present -> ????
* exiv2 absent -> don't support exiv2 features

You can see the difference in `configure` output in these two build logs: Ubuntu [doesn't support](https://travis-ci.com/ajnelson-nist/dfxml/jobs/186461680#L289) exiv2 (v0.25), macOS [does](https://travis-ci.com/ajnelson-nist/dfxml/jobs/186461681#L175) (exiv2 v0.27), though both have the exiv2 package installed.

Could you please clarify the objectives with documentation in `dfxml_configure.m4`?

**Comment by linxon** [comment]
this patch oriented for gentoo based distros where exiv2 version is not less 0.27.0

below i can provide a complete solution:
```diff
diff -ur a/src/dfxml/src/dfxml_configure.m4 b/src/dfxml/src/dfxml_configure.m4
--- a/src/dfxml/src/dfxml_configure.m4	2019-03-20 20:13:33.474143000 +0300
+++ b/src/dfxml/src/dfxml_configure.m4	2019-03-20 21:44:54.506728434 +0300
@@ -13,7 +13,15 @@
 AC_CHECK_FUNCS([fork gmtime_r getuid gethostname getpwuid getrusage mkstemp vasprintf ])
 
 AC_LANG_PUSH(C++)
-AC_CHECK_HEADERS([exiv2/image.hpp])
+PKG_CHECK_MODULES([EXIV2], [exiv2 >= 0.27.0], [
+	AC_DEFINE([HAVE_NEW_EXIV2], [1], [Add support new EXIV2 version])
+	AC_CHECK_HEADERS([exiv2/image.hpp exiv2/version.hpp], [], [], [
+	#include <exiv2/exiv2.hpp>
+	#ifdef EXIV2_VERSION
+	#include <exiv2/version.hpp>
+	#endif
+	])
+], [AC_CHECK_HEADERS([exiv2/image.hpp])])
 AC_LANG_POP()    
 
 
diff -ur a/src/dfxml/src/dfxml_writer.cpp b/src/dfxml/src/dfxml_writer.cpp
--- a/src/dfxml/src/dfxml_writer.cpp	2019-03-20 21:45:44.443122000 +0300
+++ b/src/dfxml/src/dfxml_writer.cpp	2019-03-20 21:44:37.497956394 +0300
@@ -646,6 +646,9 @@
 #include <exiv2/image.hpp>
 #include <exiv2/exif.hpp>
 #include <exiv2/error.hpp>
+#if HAVE_NEW_EXIV2
+#include <exiv2/version.hpp>
+#endif
 #endif
 
 #ifdef HAVE_HASHDB
```

**Comment by linxon** [comment]
if you do nothing, then when compiling you get this error:
Selection_303

**Comment by ajnelson-nist** [comment]
Thank you for the additional context.  That compiler error's a definite problem - an API change between 0.25 and 0.27?

The macro should still support exiv2 as best as possible.  By that, I mean Ubuntu's exiv2 support shouldn't be removed.  Your `#if` wrapping looks right in that patch.

I'm also a little confused why you're getting a compiler error but the Travis build isn't.  Any suggestions on how to reconcile that difference?  Could you update the ` check_for_recent_exiv2_version` branch's `.travis.yml` to catch this?

Also, as a soft nit, "`NEW`" is kind of a doomed variable label.  Could the variable be something like "`HAVE_EXIV2_API_0_27`"?  (I'm open to less-ugly suggestions.  But `NEW` won't stand the test of time.)

**Comment by linxon** [comment]
yeah. Because this is my first commits and i did not have to do this before ^_^
that's why I'm not going to do pull request before you check this

**Comment by ajnelson-nist** [comment]
I see.  Well, I am happy that you've identified a build issue between Bulk Extractor and hashdb, so let's do what we can to fix that.

I think it'll be important to keep exiv2 support as best as possible.  If you can trigger a build failure like what you screenshotted, that will be helpful for us to confirm the issue outside your environment.  (I believe it's a problem, but I don't see how to reproduce it.)  The autoconf macro may need to be re-done with something like checking for exiv2 being *present*, and then comparing the version for the new autotools variable -- maybe with [`ax_compare_version`](https://www.gnu.org/software/autoconf-archive/ax_compare_version.html)?

**Comment by linxon** [comment]
unfortunately i cannot trigger and test this failure insofar as i don't use other distros in current moment. But i can download latest version the Ubuntu and launch compiling later

failures only appears when compiling [bulk_extractor](https://github.com/simsong/bulk_extractor/issues/89#issuecomment-473775853) using exiv2-0.27.0 in my machine
if you are downgrade the exiv2 to 0.26.0 — build ends with success

**Pull request closed without merging**
