### PR TITLE
Move to new repositories

### PR DESCRIPTION
**Pull request by ajnelson-nist**

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
@simsong , here's the PR to signal the move.

@jgru , thanks for the discussion to help move this along.

**Review by simsong — APPROVED** [review]

**Comment by ajnelson-nist** [comment]
Thanks!  PR coming for the C++ code base soon to remove its Python.

**Comment by simsong** [comment]
Hm. Seems that we should have just renamed the repository and we could have kept the issues.

**Comment by ajnelson-nist** [comment]
I'm not sure what guarantees Github will make about preserving 30x-redirects when a repository is renamed, though.  I remember seeing red text from Github's interface saying we shouldn't rely on it.

**Comment by chhajedji** [comment]
May I please know where the location of new repository and this file is?

**Comment by ajnelson-nist** [comment]
@chhajedji The [README](https://github.com/simsong/dfxml#readme) of this repository lists the new locations.

**Pull request merged**
