### PR TITLE
Apply debian patch 0002-reproducible-build.patch

### PR DESCRIPTION
**Pull request by olibre**
I have checked the debian patches at https://packages.debian.org/sid/tcpflow
This is the pull request to avoid pacthes within issues as https://github.com/simsong/dfxml/issues/16

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
I've run `./bootstrap.sh && ./configure && make && make check` in the `src/` directory before and after applying the patch.  Exit status `0`.  Looks good to merge to me.

**Comment by simsong** [comment]
Sounds good. I'd like to move to a better unit test framework. What do you think of gtest?

**Comment by simsong** [comment]
Thanks!

**Comment by ajnelson-nist** [comment]
I don't have any experience with gtest (== GoogleTest?).  Accompanying: no opinion for or against.

**Comment by simsong** [comment]
If you are looking for a fun 3:35pm friday afternoon project, why don't you take a look and try to implement gtest?

Another thing we've been asked to look at is transitioning from automake to cmake.

**Comment by olibre** [comment]
GTest is a good choice because:

- GTest is a well known testing framework and many tcpflow contributors will easily extend the tcpflow tests
- GTest is well documented
- GTest is continuously maintained

For your information, in case you are fluent in French,  
I am maintaining a training about GUTs = Great Unit Tests  
http://olibre.github.io/GreatPractices/unit-test/reveal.html#/ 

In the slides after #/15 I present some very interesting testing frameworks for C++  
http://olibre.github.io/GreatPractices/unit-test/reveal.html#/15

* https://github.com/philsquared/Catch
* https://github.com/jimporter/mettle
* https://github.com/rollbear/trompeloeil
* https://github.com/TankerApp/mockaron
* https://github.com/grogers0/CppQuickCheck
* https://github.com/thejohnfreeman/autocheck
* https://github.com/emil-e/rapidcheck

I have planed to produce a full translation in English, but I do it when I am motivated and when I have time... (there are still many TODOs..)

**Pull request merged**
